"""phase 13 knowledge conflicts table

Revision ID: f3be66d8c56f
Revises: 3db21e213b92
Create Date: 2026-08-10 20:09:04.203985+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f3be66d8c56f'
down_revision: str | None = '3db21e213b92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_conflicts',
    sa.Column('claim_a_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('claim_a_document_id', sa.Uuid(), nullable=False),
    sa.Column('claim_a_content', sa.Text(), nullable=False),
    sa.Column('claim_b_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('claim_b_document_id', sa.Uuid(), nullable=False),
    sa.Column('claim_b_content', sa.Text(), nullable=False),
    sa.Column('contradiction_score', sa.Float(), nullable=False),
    sa.Column('preferred_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_a_chunk_id'], ['document_chunks.id'], name=op.f('fk_knowledge_conflicts_claim_a_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_a_document_id'], ['documents.id'], name=op.f('fk_knowledge_conflicts_claim_a_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_chunk_id'], ['document_chunks.id'], name=op.f('fk_knowledge_conflicts_claim_b_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_document_id'], ['documents.id'], name=op.f('fk_knowledge_conflicts_claim_b_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_chunk_id'], ['document_chunks.id'], name=op.f('fk_knowledge_conflicts_preferred_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_conflicts'))
    )
    op.create_index(op.f('ix_knowledge_conflicts_claim_a_chunk_id'), 'knowledge_conflicts', ['claim_a_chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_conflicts_claim_a_document_id'), 'knowledge_conflicts', ['claim_a_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_conflicts_claim_b_chunk_id'), 'knowledge_conflicts', ['claim_b_chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_conflicts_claim_b_document_id'), 'knowledge_conflicts', ['claim_b_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_conflicts_claim_b_document_id'), table_name='knowledge_conflicts')
    op.drop_index(op.f('ix_knowledge_conflicts_claim_b_chunk_id'), table_name='knowledge_conflicts')
    op.drop_index(op.f('ix_knowledge_conflicts_claim_a_document_id'), table_name='knowledge_conflicts')
    op.drop_index(op.f('ix_knowledge_conflicts_claim_a_chunk_id'), table_name='knowledge_conflicts')
    op.drop_table('knowledge_conflicts')
    # ### end Alembic commands ###
