"""phase 11 version comparisons table

Revision ID: a1972fda61bb
Revises: f802a56c5738
Create Date: 2026-08-10 18:47:54.219822+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a1972fda61bb'
down_revision: str | None = 'f802a56c5738'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_comparisons',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('from_version_id', sa.Uuid(), nullable=True),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('from_version_number', sa.Integer(), nullable=True),
    sa.Column('to_version_number', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('text_similarity', sa.Float(), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('replaced_count', sa.Integer(), nullable=False),
    sa.Column('added_sentences', sa.JSON(), nullable=False),
    sa.Column('removed_sentences', sa.JSON(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('drift_magnitude', sa.String(length=20), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('vectors_added', sa.Integer(), nullable=False),
    sa.Column('graph_synced', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_version_comparisons_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_version_id'], ['document_versions.id'], name=op.f('fk_version_comparisons_from_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_version_id'], ['document_versions.id'], name=op.f('fk_version_comparisons_to_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_comparisons'))
    )
    op.create_index(op.f('ix_version_comparisons_document_id'), 'version_comparisons', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_comparisons_document_id'), table_name='version_comparisons')
    op.drop_table('version_comparisons')
    # ### end Alembic commands ###
