"""phase 12 concept drift reports table

Revision ID: 3db21e213b92
Revises: a1972fda61bb
Create Date: 2026-08-10 19:39:48.904678+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3db21e213b92'
down_revision: str | None = 'a1972fda61bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_drift_reports',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('old_version_id', sa.Uuid(), nullable=True),
    sa.Column('new_version_id', sa.Uuid(), nullable=False),
    sa.Column('old_version_number', sa.Integer(), nullable=True),
    sa.Column('new_version_number', sa.Integer(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('drift_type', sa.String(length=20), nullable=False),
    sa.Column('changed_chunks', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_concept_drift_reports_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_version_id'], ['document_versions.id'], name=op.f('fk_concept_drift_reports_new_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_version_id'], ['document_versions.id'], name=op.f('fk_concept_drift_reports_old_version_id_document_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_drift_reports'))
    )
    op.create_index(op.f('ix_concept_drift_reports_document_id'), 'concept_drift_reports', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_drift_reports_document_id'), table_name='concept_drift_reports')
    op.drop_table('concept_drift_reports')
    # ### end Alembic commands ###
